### ISSUE TITLE
Declaration in `record` macro is incorrectly interpreted as useless assignment

### ISSUE THREAD

**Issue by straight-shoota** [veelenga/ameba#77]
```cr
record Foo, foo = "foo" # Useless assignment to variable `foo`
```

I guess all assignments used as macro arguments shouldn't be treated as a useless assign because you can't know how it will be used in the macro.

**Comment by veelenga** [comment]
Thanks for reporting. I'm aware of this case and have seen it a couple of times. The problem, there is no easy way to avoid it, because it is parsed as:

`record(Foo, foo = "foo")`

where

`record` is a `Crystal::Call`
`Foo` is a `Crystal::Path`
`foo = "foo"` is a `Crystal::Assign`

which is bacisally the same as `my_method(Foo, foo = "foo")`

**Comment by straight-shoota** [comment]
Ah, yes. Well, that would require to proceed into the semantic stage of the compiler.

Maybe, as a quick fix for a large number of affected cases, calls to `record` could just be hard coded as "probably a macro" as it is very likely to have assignments in it's arguments.

**Comment by straight-shoota** [comment]
Yes. `record` expands to `struct` so it needs to be declared in a static scope.

**Comment by straight-shoota** [comment]
Ooops, wrong button.
